[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dealgraph"
version = "0.0.1"
description = "A streaming ingestion pipeline for RAG, with optimization based on QA-GNN."
readme = {file= "README.md", content-type = "text/markdown"}
authors = [
  {name = "Mathys Muganga", email = "rassou.muganga@gmail.com"}
]
keywords = ["RAG", "DataEngineering", "ETL", "Streaming", "Kafka"]
requires-python = ">=3.11"
dependencies = [
  "ipykernel",
  "numpy",
  "pandas"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["infra*", "pipeline*"]
exclude = ["docs*"]

